version: "3"
services:
  hapi-fhir:
    build: .
    image: graphite/hapi-fhir
    container_name: hapi-fhir
    restart: on-failure
    depends_on:
      - fhir-db
    ports:
      - "8080:8080"
    environment:
      DB_URL: "jdbc:postgresql://fhir-db:5432/hapi"
      DB_USER: "admin"
      DB_PASS: "admin"
      TERMINOLOGY_URL: "https://dev-pivot-app.infra.graphitehealth.io/SymedicaldevpivotFHIRServices/r4/"
  fhir-db:
    image: postgres:14.6-alpine
    container_name: fhir-db
    restart: always
    environment:
      POSTGRES_DB: "hapi"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - hapi-fhir-db:/var/lib/postgresql/data
volumes:
  hapi-fhir-db: